apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.Application.Name }}-preview
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /
spec:
  rules:
  - host: {{ .Values.Application.Dns }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.Application.Name }}-preview
            port:
              name: http
